In [33]:
#Importing Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import torch

In [34]:
#Loading the Dataset
df = pd.read_csv('dataset/student_performance.csv')
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [35]:
# Dropping the student_id Column
df = df.drop(["student_id"], axis=1)
df.head()

,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,18.5,95.6,3.8,97.9,A
1,14.0,80.0,2.5,83.9,B
2,19.5,86.3,5.3,100.0,A
3,25.7,70.2,7.0,100.0,A
4,13.4,81.9,6.9,92.0,A

In [36]:
# Encoding the Target Column - converting grades to numbers (A=0, B=1, C=2, D=3, F=4)
le = LabelEncoder()
df['grade'] = le.fit_transform(df['grade'])

print("Classes:", le.classes_)
print(df['grade'].value_counts())

Classes: ['A' 'B' 'C' 'D' 'F']
grade
0    548644
1    258174
2    141980
3     44998
4      6204
Name: count, dtype: int64

In [37]:
df.head()

,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,18.5,95.6,3.8,97.9,0
1,14.0,80.0,2.5,83.9,1
2,19.5,86.3,5.3,100.0,0
3,25.7,70.2,7.0,100.0,0
4,13.4,81.9,6.9,92.0,0

In [38]:
#Splitting Features and Target
x=df.drop(["grade"], axis=1)
y=df["grade"]

In [39]:
#checking the features
x.head()

,weekly_self_study_hours,attendance_percentage,class_participation,total_score
0,18.5,95.6,3.8,97.9
1,14.0,80.0,2.5,83.9
2,19.5,86.3,5.3,100.0
3,25.7,70.2,7.0,100.0
4,13.4,81.9,6.9,92.0

In [40]:
#Checking the targets
y.head()

0    0
1    1
2    0
3    0
4    0
Name: grade, dtype: int64

In [41]:
#Splitting into Train and Test Sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42, stratify=y)

print("Train size :", x_train.shape)
print("Test size  :", x_test.shape)

Train size : (800000, 4)
Test size  : (200000, 4)

In [48]:
# Saving Preprocessed Data to CSV files
x_train.to_csv('preprocessed_data/x_train.csv', index=False)
x_test.to_csv('preprocessed_data/x_test.csv',   index=False)
y_train.to_csv('preprocessed_data/y_train.csv', index=False)
y_test.to_csv('preprocessed_data/y_test.csv',   index=False)

In [ ]:
#Scalling the features for PyTorch

scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [43]:
# Converting Scaled Data to PyTorch Tensors
x_train_tensor=torch.tensor(x_train_scaled, dtype=torch.float32)
x_test_tensor=torch.tensor(x_test_scaled, dtype=torch.float32)

y_train_tensor=torch.tensor(y_train.values, dtype=torch.long)
y_test_tensor =torch.tensor(y_test.values,  dtype=torch.long)

In [50]:
# Saving Tensors
torch.save(x_train_tensor, "preprocessed_data/x_train_tensor.pt")
torch.save(x_test_tensor,  "preprocessed_data/x_test_tensor.pt")
torch.save(y_train_tensor, "preprocessed_data/y_train_tensor.pt")
torch.save(y_test_tensor,  "preprocessed_data/y_test_tensor.pt")